name: web documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinxnotes.strike
      - name: Sphinx build
        run: |
          sphinx-build webdocs _build
#
      - name: Old Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          timeout: 600000
#          error_count: 10
#          reporting_interval: 5000
          artifact_name: github-pages
#          preview: false
#
#      - name: Copy tutorials
#        run: |
#           cp -v tutorials.html _build/
#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
#        with:
#          publish_branch: gh-pages
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: _build/
#          force_orphan: true
