name: web documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinxnotes.strike
      - name: Sphinx build
        run: |
          sphinx-build webdocs _build
      - name: Copy tutorials
        run: |
           cp -v tutorials.html _build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
