# Develop code to build markup files into HTML
# 
name: test md to HTML

on: [workflow_dispatch] 

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:       # Build web pages
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Find tutorials
        run: |
          which pandoc
          which sed
          cd MDtutorials
          ls
          for path in ./*; do
            [ -d "${path}" ] || continue # if not a directory, skip
            dirname="$(basename "${path}")"
            mkdir -v ../$dirname
            for fil in $dirname/*.md; do
              echo $fil
              ls -l $fil
            done
          done
        
